### ISSUE TITLE
Buuz135's mods

### ISSUE THREAD

**Issue by Buuz135** [AllTheMods/ATC2#11]
https://www.curseforge.com/minecraft/mc-mods/portality/files/2741361
depends on
https://www.curseforge.com/minecraft/mc-mods/titanium/files/2741295

**Comment by SkySom** [comment]
Titanium Crashes on server side: https://gist.github.com/SkySom/56ae43784b613d23d10103cbbac31f6b

**Comment by Buuz135** [comment]
Fixed https://www.curseforge.com/minecraft/mc-mods/titanium/files/2743803 and https://www.curseforge.com/minecraft/mc-mods/portality/files/2743807

**Comment by SkySom** [comment]
added in 2.2.0
