### ISSUE TITLE
New Mod Additions

### ISSUE THREAD

**Issue by Blueletric** [AllTheMods/ATC2#12]

**Comment by Blueletric** [comment]
**Buuzs mods** 
(https://www.curseforge.com/minecraft/mc-mods/portality/files/2741361)
depends on
https://www.curseforge.com/minecraft/mc-mods/titanium/files/2741295

**Comment by Blueletric** [comment]
Olys suggestions:
https://www.curseforge.com/minecraft/mc-mods/practical-tools
https://www.curseforge.com/minecraft/mc-mods/not-enough-wands

**Comment by Shadows-of-Fire** [comment]
https://www.curseforge.com/minecraft/mc-mods/toast-control/files/2740943

**Comment by Darkere** [comment]
https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/clumps/files/2741398

**Comment by Blueletric** [comment]
https://www.curseforge.com/minecraft/mc-mods/classic-bars Youre welcome IItem

**Comment by Tfarcenim** [comment]
bad idea, it has 0 config files and won't have any until forge gets a config gui

**Comment by SkySom** [comment]
Mods added other than Classic bars until IItemstack okays it.
