### ISSUE TITLE
[Crash]: I right-clicked a furnace and it CME'd

### ISSUE THREAD

**Issue by Lanse505** [AllTheMods/ATC2#16]
I hope @SkySom is happy that I've now reported that I right-clicked a furnace and it CME'd the server. Cause otherwise I'll have to report that I right-clicked a furnace with more details as to why it crashed with a CME. I think this can be fixed by updating forge though?

To reiterate what I did was right-click a furnace which caused a CME on the server.
However this can probably be fixed by updating forge, and this would be the fact that I right-clicked a furnace which caused a CME.

**Comment by SkySom** [comment]
Updating forge in 2.1.0 should help.
