### ISSUE TITLE
Empty crafting window creates barrel upgrade

### ISSUE THREAD

**Issue by minecreatr** [AllTheMods/ATC2#5]
Having an empty crafting window will allow you to craft a barrel upgrade. A note, you have to put an item in and out to update the window in the first place.
![wat_barrel](https://user-images.githubusercontent.com/6035929/61163535-8bfec200-a4dc-11e9-95a3-cd022e4434ee.JPG)

**Comment by Tfarcenim** [comment]
vanilla bug, workaround is to add silver/copper ingots

**Comment by Tfarcenim** [comment]
update to 1.2 as a temp fix, copper/silver tags were removed so no more free stuff.  Logspam will occur because of exceptions, but ignore it until forge/mojang fixes it I guess.

**Comment by SkySom** [comment]
Fixed in 2.1.0
