### ISSUE TITLE
Morpheus Does Nothing When You Sleep

### ISSUE THREAD

**Issue by kjmaster1** [AllTheMods/ATC2#7]
Morpheus-1.14.3-4.1.20
Forge-1.14.3-27.0.50
https://github.com/Quetzi/Morpheus/issues/61

**Comment by SkySom** [comment]
I added a Datapack that should do the sleeping stuff, WIll remove Morpheus until it's fixed

**Comment by SkySom** [comment]
Morphous removed in 2.1.0, datapack seems to work.
